general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono NF"
# family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
# family = "CaskaydiaCove Nerd Font"
style = "Regular"
